### ISSUE TITLE
Implement surface importer

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#11]
# Overview
The surface importer allows the user to select MountainsMap .sur files to be imported for analysis. However, since these surfaces will need to be initially analyzed through scale-sensitive analysis, these selected surfaces will be fed into MountainsMap for analysis. In order to accomplish this, the application will assume control of the user's mouse and keyboard. These results will then be fed into the multiscale app as they normally would.

Before taking mouse/keyboard control, the user will first be given the option for whether to run either scale-sensitive or complexity analysis. From there, they then have the choice of length scale/complexity or area scale/complexity. The user also should have the choice of the directory to save the results files.

# Tasks
- [x] Information/requirement popup (#89)
- [x] Scale-sensitive or complexity selection menu (#59)
- [x] Length/area analysis selection menu (#60)
- [x] Results directory selection (#63)
- [x] Error dialog for incorrect data entry (#66)
- [x] File overwrite dialog? (#67)
- [x] Mountains external script generation and windows registery for quick execution (#62)
- [x] Use pre-generated mountains template file for improving external script efficiency (#61)
- [x] Use `pyautogui` for mouse and keyboard control within Mountains (#68)
- [x] Saving results files based on surface file names (#69)
- [x] Multithreaded termination detection using hotkey/mouse (similar to `pyautogui`'s failsafe) (#70)

**Comment by MatthewSpofford** [comment]
Removed almost all of this tool from the v0.4.0 milestone. Early termination hotkey and progress bar are not necessarily needed for this release.
