### ISSUE TITLE
Cleanup surface importer dialogs

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#115]
- [ ] "Do not show this again" checkbox for info dialog
- [ ] Keep import options and information dialog in one window
- [ ] Remove whitespace and tide up the config dialog
- [ ] Implement a continue or next button to go between config/info menu, similar to a Wizard GUIs
- [ ] Increase the length of results folder text box
