### ISSUE TITLE
Curve fit window overhaul

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#121]
- [ ] Radio buttons for regression/scale R^2 options
- [x] Remove errors being displayed during best fit runtime
- [x] After running best fit, does not display initial results
- [ ] Should get as close as possible to the features offered in sfrax

Sfrax example:
![image](https://user-images.githubusercontent.com/10645029/93952022-d81ad880-fd15-11ea-8d7e-2aad01496e60.png)
