### ISSUE TITLE
Clean up repetitive code

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#33]
- [x] Clean up `CanvasPanel`:
    - [x] Restructure regression curve fit plot functions in `CanvasPanel` (#26)
    - [x] Restructure `R2byScalePlot` plot functions, remove repetitiveness (#45)
    - [X] ~~Merge `SclbyAreaPlot`'s draw area plot and complexity plot functions (#46)~~
    - [x] Restrucutre/simplify `RegressionSelectPlot` plot functions (#47)
- [x] Regression fit graph creation dialog button is incredibly repetitive in `main.py` (#41)
- [X] ~~Could possible clean up `CurveFit`'s use of scipy's `curve_fit`~~
- [x] Replace `CurveFit` instance methods with static methods (#43)
- [x] Clean up `StatsTestUI`'s `FtestDialog` statistical functions, too repetitive (#48)
- [x] Merge discrimination and scale plot menu events in `main.py` (#49)
