### ISSUE TITLE
Create .MAWB file type for easy importing of previous workbooks

### ISSUE THREAD

**Issue by MatthewSpofford** [MatthewSpofford/Multiscale-Statistical-Analysis#36]
# Proposition
A new file type called **.MAWB** (**M**ulti-scale **A**nalysis **W**ork**b**ook). This workbook file will store the following data:
- [ ] Workbook name
- [ ] Generated graphs within the workbook, their position on the tree menu, as well as names
- [ ] The data stored within the workbook
- [ ] Piggy-back off of a previously written file type (Excel spreadsheet file type?)
- [ ] Seperate button on "File" menu to open workbooks

# Laying the Groundwork
The first option would be to write the object data into a file. No compression, nothing fancy in any way. However, this could possibly build upon something such as .xlsx (Excel).

**Comment by MatthewSpofford** [comment]
This idea, while sounding useful on paper, may not be practical.
